global using MathStorm.Common.DTOs;
global using MathStorm.Common.Models;
global using MathStorm.Console.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Spectre.Console;
global using System.Text;
global using System.Text.Json;