global using MathStorm.Core;
global using MathStorm.Core.DTOs;
global using MathStorm.Core.Models;
global using MathStorm.Console.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Spectre.Console;
global using System.Text;