# You can also use the Swagger UI: https://Math.Storm.luppes.com/api/swagger/ui

@baseUrl = https://Math.Storm.luppes.com/api
@APIKey = 

### ---------------------------------------------------------------------------
### Get a random joke
GET {{baseUrl}}/joke HTTP/1.1
APIKey: {{APIKey}}

### ---------------------------------------------------------------------------
### Get all jokes in a category
GET {{baseUrl}}/joke/category/Thanksgiving HTTP/1.1
APIKey: {{APIKey}}
