# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to run the smoke tests only
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 5.smoke.test.webapp
run-name: '5 - [${{ inputs.deployEnvironment }}] Smoke Test by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev' 
        type: environment
      logLevel:
        description: Log level
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: read
          
# ------------------------------------------------------------------------------------------------------------------------
jobs:
  run-smoke-test:
    name: Smoke Test ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-smoke-test.yml
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      testPath: 'Tests/playwright/ui-tests'
      testType: 'ui'
